[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200

[profile.default.fmt]
line_length = 100
tab_width = 4
bracket_spacing = true

[rpc_endpoints]
pasifika = "https://rpc.pasifika.xyz"
localhost = "http://127.0.0.1:8545"

# Etherscan verification not available for Pasifika Data Chain
# [etherscan]
# pasifika = { key = "", chain = 999888 }
